In [2]:
import pandas as pd

df = pd.read_csv("weather.csv")
df

     outlook temperature humidity  windy play
0   overcast         hot     high  False  yes
1   overcast        cool   normal   True  yes
2   overcast        mild     high   True  yes
3   overcast         hot   normal  False  yes
4      rainy        mild     high  False  yes
5      rainy        cool   normal  False  yes
6      rainy        cool   normal   True   no
7      rainy        mild   normal  False  yes
8      rainy        mild     high   True   no
9      sunny         hot     high  False   no
10     sunny         hot     high   True   no
11     sunny        mild     high  False   no
12     sunny        cool   normal  False  yes
13     sunny        mild   normal   True  yes

In [2]:
def foo(df,colNames, values):
    l = []
    for i in range(len(colNames)):
        l.append(df[colNames[i]] == values[i])
        
#     return df.loc()
#     print(l)
    
    x = l[0]
    for i in range(1,len(l)):
        x = x&l[i]
        
    return df.loc[x]

newDf = foo(df,["temperature"], ["hot"])
newDf

     outlook temperature humidity  windy play
0   overcast         hot     high  False  yes
3   overcast         hot   normal  False  yes
9      sunny         hot     high  False   no
10     sunny         hot     high   True   no

In [6]:
def findVariables(df, col):
    l = []
    for elem in df[col]:
    	if elem not in l:
    		l.append(elem)
    return l

x = findVariables(newDf, "outlook")
x

['overcast', 'sunny']

In [8]:
def getCardinality(df, col):
    return len(findVariables(df,col))

y = getCardinality(newDf, "outlook")
y

2

In [21]:
# Desde aqui importa <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

m = [[0,1,1,1,0],
     [1,0,0,1,1],
     [0,0,0,1,1],
     [0,0,0,0,0],
     [1,1,1,1,0]]

def getParents(g,df):
    fathers = []
    res = []
    colNames = list(df.columns)
    
    for col in range(len(g)):
        aux = []
        for row in range(len(g)):
            if(m[col][row] == 1):
                aux.append(cols[row])
        fathers.append(aux)

    for i in range(len(g)):
        yield [colNames[i],fathers[i]]
    
    #return res

for i in getParents(m,df):
    print(i)

['outlook', ['temperature', 'humidity', 'windy']]
['temperature', ['outlook', 'windy', 'play']]
['humidity', ['windy', 'play']]
['windy', []]
['play', ['outlook', 'temperature', 'humidity', 'windy']]

In [ ]:
class rb:
    def __init__(self,g, df,a):
        self.dag = g
        self.cpbs = [] # => tienes que correr calc() para llenarlo
        self.alpha = a
    
    def calc(self):
        for elem in getParents(g,df):
            if(len(elem[1] == 0)):
                self.cpbs.append([elem,estimar_marginal(df,elem[0],self.alpha)])
            else:
                self.cpbs.append([elem,estimar_condicional(df,elem[0],elem[1],self.alpha)])